### PR TITLE
Adding persistant delivery mode

### PR DESCRIPTION
**Pull request by djw8605**

### CODE REVIEW

**Review by bbockelm — CHANGES_REQUESTED** [review]
I thought I saw an `enum` in the upstream package - better to use that than a magic number.  I think this is the relevant example: https://github.com/streadway/amqp/blob/3d520d05b74cc137bfac4ee6cd40d52cda7810ee/examples_test.go#L357

Also, can you add a small comment about why we want persistent mode?

**Comment by bbockelm** [comment]
Additionally - can you leave notes on the request on what testing you did?

**Review by bbockelm — APPROVED** [review]
LGTM, pending some description of testing performed.

**Comment by djw8605** [comment]
@bbockelm I added the test for delivery mode.

**Comment by bbockelm** [comment]
Oh nifty - that's easy enough!  Thanks!

**Pull request merged**
